services:
  microservicio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@bdfullstack1_high?TNS_ADMIN=/app/oracle_wallet/
      - SPRING_DATASOURCE_USERNAME=ADMIN
      - SPRING_DATASOURCE_PASSWORD=Oracle12345!
      - ORACLE_JDBC_FANENABLED=false
    restart: always